export const BASE_URL = "http://localhost:8080";
export const PARSE_URL = "http://141.147.0.104:7500/parse";
export const SKILL_URL = "http://141.147.0.104:7500/skills";
export const SET_SHARED = "SET_SHARED";
export const SET_USER_PROFILE = "SET_USER_PROFILE";
export const SET_COMPANY = "SET_COMPANY";
export const SET_ADD_JOB = "SET_ADD_JOB";
export const SET_EDIT_JOB = "SET_EDIT_JOB";
export const SET_PROFILE_FORM = "SET_PROFILE_FORM";
export const UPDATE_PROFILE_FORM = "UPDATE_PROFILE_FORM";
export const RESET_ADD_JOB = "RESET_ADD_JOB";
export const SET_CHAT = "SET_CHAT";
export const SET_CONVERSATIONS = "SET_CONVERSATIONS";
export const UPDATE_MESSAGES = "UPDATE_MESSAGES";
export const RESET_COMPANY = "RESET_COMPANY";
export const RESET_SHARED = "RESET_SHARED";
export const RESET_CHAT = "RESET_CHAT";
export const APPLY_JOB_FILTER = "APPLY_JOB_FILTER";
export const APPLY_USER_CHAT_SEARCH_FILTER = "APPLY_USER_CHAT_SEARCH_FILTER";
export const APPLY_COMPANY_CHAT_SEARCH_FILTER =
  "APPLY_COMPANY_CHAT_SEARCH_FILTER";
export const FILTER_JOB_APPLICATIONS = "FILTER_JOB_APPLICATIONS";
export const FILTER_USER_JOB_APPLICATIONS = "FILTER_USER_JOB_APPLICATIONS";

